from __future__ import annotations
from typing import Protocol
from app.domain.entities import Project, Task

class ProjectRepository(Protocol):
    def add(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project: ...
    def list(self) -> list[Project]: ...

class TaskRepository(Protocol):
    def add(self, task: Task) -> None: ...
    def get(self, task_id: str) -> Task: ...
    def delete(self, task_id: str) -> None: ...
    def list_by_project(self, project_id: str) -> list[Task]: ...